In [2]:
pip install pandapower[all]

Requirement already satisfied: pandapower[all] in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.14.11)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: C:\Users\julie\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas>=1.0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (2.2.2)
Requirement already satisfied: networkx>=2.5 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (3.3)
Requirement already satisfied: scipy<1.14 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (1.13.1)
Requirement already satisfied: numpy<2.0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (1.26.4)
Requirement already satisfied: packaging in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (24.0)
Requirement already satisfied: tqdm in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (4.66.5)
Requirement already satisfied: deepdiff in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (8.0.1)
Requirement already satisfied: numpydoc in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (1.8.0)
Requirement already satisfied: sphinx in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (7.4.7)
Requirement already satisfied: sphinx-rtd-theme in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (2.0.0)
Requirement already satisfied: plotly>=3.1.1 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (5.24.1)
Requirement already satisfied: matplotlib<3.9 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (3.8.4)
Requirement already satisfied: igraph in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (0.11.6)
Requirement already satisfied: geopandas<1.0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (0.14.4)
Requirement already satisfied: geojson in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (3.1.0)
Requirement already satisfied: pytest~=8.1 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (8.3.3)
Requirement already satisfied: pytest-xdist in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (3.6.1)
Requirement already satisfied: ortools in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (9.11.4210)
Requirement already satisfied: lightsim2grid~=0.8.1 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (0.8.2)
Requirement already satisfied: xlsxwriter in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (3.2.0)
Requirement already satisfied: openpyxl in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (3.1.5)
Requirement already satisfied: cryptography in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (43.0.1)
Requirement already satisfied: psycopg2 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (2.9.9)
Requirement already satisfied: matpowercaseframes in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (1.0.8)
Requirement already satisfied: power-grid-model-io in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (1.2.101)
Requirement already satisfied: numba>=0.25 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandapower[all]) (0.60.0)
Requirement already satisfied: fiona>=1.8.21 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from geopandas<1.0->pandapower[all]) (1.10.0)
Requirement already satisfied: pyproj>=3.3.0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from geopandas<1.0->pandapower[all]) (3.6.1)
Requirement already satisfied: shapely>=1.8.0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from geopandas<1.0->pandapower[all]) (2.0.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<3.9->pandapower[all]) (1.3.0)
Requirement already satisfied: cycler>=0.10 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<3.9->pandapower[all]) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<3.9->pandapower[all]) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<3.9->pandapower[all]) (1.4.7)
Requirement already satisfied: pillow>=8 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<3.9->pandapower[all]) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<3.9->pandapower[all]) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<3.9->pandapower[all]) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from numba>=0.25->pandapower[all]) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=1.0->pandapower[all]) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=1.0->pandapower[all]) (2024.1)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from plotly>=3.1.1->pandapower[all]) (9.0.0)
Requirement already satisfied: iniconfig in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pytest~=8.1->pandapower[all]) (2.0.0)
Requirement already satisfied: pluggy<2,>=1.5 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pytest~=8.1->pandapower[all]) (1.5.0)
Requirement already satisfied: colorama in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pytest~=8.1->pandapower[all]) (0.4.6)
Requirement already satisfied: cffi>=1.12 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from cryptography->pandapower[all]) (1.16.0)
Requirement already satisfied: orderly-set==5.2.2 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from deepdiff->pandapower[all]) (5.2.2)
Requirement already satisfied: texttable>=1.6.2 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from igraph->pandapower[all]) (1.7.0)
Requirement already satisfied: tabulate>=0.8.10 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from numpydoc->pandapower[all]) (0.9.0)
Requirement already satisfied: sphinxcontrib-applehelp in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sphinx->pandapower[all]) (2.0.0)
Requirement already satisfied: sphinxcontrib-devhelp in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sphinx->pandapower[all]) (2.0.0)
Requirement already satisfied: sphinxcontrib-jsmath in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sphinx->pandapower[all]) (1.0.1)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sphinx->pandapower[all]) (2.1.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sphinx->pandapower[all]) (2.0.0)
Requirement already satisfied: sphinxcontrib-qthelp in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sphinx->pandapower[all]) (2.0.0)
Requirement already satisfied: Jinja2>=3.1 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sphinx->pandapower[all]) (3.1.3)
Requirement already satisfied: Pygments>=2.17 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sphinx->pandapower[all]) (2.17.2)
Requirement already satisfied: docutils<0.22,>=0.20 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sphinx->pandapower[all]) (0.20.1)
Requirement already satisfied: snowballstemmer>=2.2 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sphinx->pandapower[all]) (2.2.0)
Requirement already satisfied: babel>=2.13 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sphinx->pandapower[all]) (2.14.0)
Requirement already satisfied: alabaster~=0.7.14 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sphinx->pandapower[all]) (0.7.16)
Requirement already satisfied: imagesize>=1.3 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sphinx->pandapower[all]) (1.4.1)
Requirement already satisfied: requests>=2.30.0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sphinx->pandapower[all]) (2.31.0)
Requirement already satisfied: et-xmlfile in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from openpyxl->pandapower[all]) (1.1.0)
Requirement already satisfied: absl-py>=2.0.0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ortools->pandapower[all]) (2.1.0)
Requirement already satisfied: protobuf<5.27,>=5.26.1 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ortools->pandapower[all]) (5.26.1)
Requirement already satisfied: immutabledict>=3.0.0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ortools->pandapower[all]) (4.2.0)
Requirement already satisfied: power-grid-model>=1.8 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from power-grid-model-io->pandapower[all]) (1.9.40)
Requirement already satisfied: pyyaml in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from power-grid-model-io->pandapower[all]) (6.0.1)
Requirement already satisfied: structlog in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from power-grid-model-io->pandapower[all]) (24.4.0)
Requirement already satisfied: execnet>=2.1 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pytest-xdist->pandapower[all]) (2.1.1)
Requirement already satisfied: sphinxcontrib-jquery<5,>=4 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sphinx-rtd-theme->pandapower[all]) (4.1)
Requirement already satisfied: pycparser in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from cffi>=1.12->cryptography->pandapower[all]) (2.21)
Requirement already satisfied: attrs>=19.2.0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from fiona>=1.8.21->geopandas<1.0->pandapower[all]) (23.2.0)
Requirement already satisfied: certifi in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from fiona>=1.8.21->geopandas<1.0->pandapower[all]) (2024.2.2)
Requirement already satisfied: click~=8.0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from fiona>=1.8.21->geopandas<1.0->pandapower[all]) (8.1.7)
Requirement already satisfied: click-plugins>=1.0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from fiona>=1.8.21->geopandas<1.0->pandapower[all]) (1.1.1)
Requirement already satisfied: cligj>=0.5 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from fiona>=1.8.21->geopandas<1.0->pandapower[all]) (0.7.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Jinja2>=3.1->sphinx->pandapower[all]) (2.1.5)
Requirement already satisfied: six>=1.5 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.7->matplotlib<3.9->pandapower[all]) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests>=2.30.0->sphinx->pandapower[all]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests>=2.30.0->sphinx->pandapower[all]) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\julie\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests>=2.30.0->sphinx->pandapower[all]) (2.2.1)

In [3]:
## PRESS PLAY
import pandapower as pp
import pandapower.networks as nw

#create empty net
net = nw.create_cigre_network_mv()

In [4]:
net

This pandapower network includes the following parameter tables:
   - bus (15 elements)
   - load (18 elements)
   - switch (8 elements)
   - ext_grid (1 element)
   - line (15 elements)
   - trafo (2 elements)
   - bus_geodata (15 elements)

In [5]:
pp.runpp(net)

In [6]:
net.res_bus

       vm_pu  va_degree       p_mw     q_mvar
0   1.030000   0.000000 -45.045732 -16.341411
1   0.991972 -36.556771  19.839000   4.637136
2   0.968147 -37.604191   0.000000   0.000000
3   0.930961 -39.330960   0.501700   0.208882
4   0.929098 -39.434973   0.431650   0.108182
5   0.927823 -39.506622   0.727500   0.182329
6   0.926321 -39.591791   0.548050   0.137354
7   0.925122 -39.589560   0.076500   0.047410
8   0.925404 -39.578992   0.586850   0.147078
9   0.924422 -39.619167   0.573750   0.355578
10  0.923174 -39.685430   0.543300   0.161264
11  0.922980 -39.696527   0.329800   0.082656
12  1.000146 -35.487100  20.010000   4.693341
13  0.995326 -35.538237   0.034000   0.021071
14  0.992553 -35.567913   0.540050   0.257713

In [7]:
# check the line percentage
net.res_line.loading_percent

0     96.482978
1     96.958807
2     37.580668
3     28.091021
4     12.122901
5      1.936801
6     33.550914
7     19.476278
8      7.294089
9     48.143637
10     9.476242
11     8.908939
12     0.084082
13     0.171049
14     0.037287
Name: loading_percent, dtype: float64

In [8]:
net.line

,name,std_type,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,df,parallel,type,in_service
0,Line 1-2,CABLE_CIGRE_MV,1,2,2.82,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
1,Line 2-3,CABLE_CIGRE_MV,2,3,4.42,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
2,Line 3-4,CABLE_CIGRE_MV,3,4,0.61,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
3,Line 4-5,CABLE_CIGRE_MV,4,5,0.56,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
4,Line 5-6,CABLE_CIGRE_MV,5,6,1.54,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
5,Line 7-8,CABLE_CIGRE_MV,7,8,1.67,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
6,Line 8-9,CABLE_CIGRE_MV,8,9,0.32,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
7,Line 9-10,CABLE_CIGRE_MV,9,10,0.77,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
8,Line 10-11,CABLE_CIGRE_MV,10,11,0.33,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
9,Line 3-8,CABLE_CIGRE_MV,3,8,1.30,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
10,Line 12-13,OHL_CIGRE_MV,12,13,4.89,0.510,0.366,10.09679,0.0,0.195,1.0,1,ol,True
11,Line 13-14,OHL_CIGRE_MV,13,14,2.99,0.510,0.366,10.09679,0.0,0.195,1.0,1,ol,True
12,Line 6-7,CABLE_CIGRE_MV,6,7,0.24,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
13,Line 11-4,CABLE_CIGRE_MV,11,4,0.49,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
14,Line 14-8,OHL_CIGRE_MV,14,8,2.00,0.510,0.366,10.09679,0.0,0.195,1.0,1,ol,True

In [9]:
net.res_trafo

,p_hv_mw,q_hv_mvar,p_lv_mw,q_lv_mvar,pl_mw,ql_mvar,i_hv_ka,i_lv_ka,vm_hv_pu,va_hv_degree,vm_lv_pu,va_lv_degree,loading_percent
0,24.429066,9.226768,-24.387928,-6.141481,0.041137,3.085287,0.133068,0.731874,1.03,0.0,0.991972,-36.556771,101.411473
1,20.616666,7.114643,-20.587971,-4.962515,0.028695,2.152128,0.111137,0.611256,1.03,0.0,1.000146,-35.487100,84.698048

In [25]:
net.line.at[10, 'in_service'] = False

In [11]:
net.switch

   bus  element et type  closed  name  z_ohm  in_ka
0    6       12  l  LBS    True  None    0.0    NaN
1    7       12  l  LBS   False    S2    0.0    NaN
2    4       13  l  LBS   False    S3    0.0    NaN
3   11       13  l  LBS    True  None    0.0    NaN
4    8       14  l  LBS   False    S1    0.0    NaN
5   14       14  l  LBS    True  None    0.0    NaN
6    0        0  t   CB    True  None    0.0    NaN
7    0        1  t   CB    True  None    0.0    NaN

In [26]:
net.switch.at[4, 'closed'] = True #switch 1
net.switch.at[1, 'closed'] = False #switch 2
net.switch.at[2, 'closed'] = False #switch 3

In [29]:
pp.runpp(net)

In [30]:
net.res_line.loading_percent

0     110.867719
1     111.371759
2      38.106237
3      28.484367
4      12.291880
5       1.967319
6      34.087808
7      19.786853
8       7.410763
9      61.945286
10           NaN
11           NaN
12      0.082930
13      0.168383
14      9.744999
Name: loading_percent, dtype: float64

In [31]:
net.res_bus.vm_pu

0     1.030000
1     0.989694
2     0.961772
3     0.918336
4     0.916446
5     0.915152
6     0.913627
7     0.910771
8     0.911059
9     0.910060
10    0.908791
11    0.908594
12    1.001790
13         NaN
14    0.909027
Name: vm_pu, dtype: float64